# Este modelo do AWS SAM foi gerado a partir da configuração da sua função. Se sua
# função tiver um ou mais acionadores, observe que os recursos da AWS associados a
# esses acionadores não estão totalmente especificados nesse modelo e incluem
# valores de espaço reservado. Abra esse modelo no AWS Infrastructure Composer ou
# em seu IDE favorito e modifique-o para especificar uma aplicação com tecnologia
# sem servidor com outros recursos da AWS.
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.
Resources:
  exercicioLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Description: ''
      MemorySize: 128
      Timeout: 3
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: arn:aws:logs:us-east-1:084828570356:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - >-
                  arn:aws:logs:us-east-1:084828570356:log-group:/aws/lambda/exercicioLambda:*
      RecursiveLoop: Terminate
      SnapStart:
        ApplyOn: None
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
